version: '3.7'
services:
  postgres:
    container_name: postgres
    ports:
      - '5432:5432'
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres_disk:/var/lib/postgresql/data
  prisma:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: backend/prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma
  backend:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: backend
    ports:
      - '5000:5000'
    environment:
      DATABASE_CONNECTION: postgresql://root:prisma@localhost:5432/dev"
    build:
      context: backend
      dockerfile: Dockerfile
  frontend:
    container_name: frontend
    depends_on:
      - backend
    ports:
      - '3000:8080'
    build:
      context: frontend
      dockerfile: Dockerfile
volumes:
  postgres_disk: